version: 2

project_name: pl

builds:
  - id: pl
    main: ./cmd/pl
    binary: pl
    env: [CGO_ENABLED=0]
    flags: [-trimpath]
    ldflags:
      - -s -w
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]
    builds_info:
      group: root
      owner: root
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^chore:"
      - "^test:"
      - "^docs:"

release:
  github:
    owner: go-faster
    name: pl
  mode: replace
  draft: false
  prerelease: auto

snapshot:
  version_template: "{{ incpatch .Version }}-next"
